import Head from "next/head";
import Image from "next/image";
import Nav from "../components/user/Nav";
import Script from "next/script";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const mahasiswa = [
    { nim: "1120100100", nama: "Rian Hidayat" },
    { nim: "1120100101", nama: "Ani mulyani" },
    { nim: "1120100102", nama: "Budiman" },
  ];
  const router = useRouter();

  const sendParamRouter = (nim) => {
    router.push(`/user/${nim}`);
  };
  return (
    <div className="container mt-4">
      <Nav />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h3>Hallo Next...</h3>
        <h3>Daftar Mahasiswa</h3>
        <ul>
          {mahasiswa.map((mhs, idx) => (
            <>
              <li key={idx}>
                <Link href={`/user/${mhs.nim}`}>
                  <a>{mhs.nim}</a>
                </Link>
                <p>{mhs.nama}</p>
                <button
                  className="btn btn-primary"
                  onClick={(e) => sendParamRouter(mhs.nim)}
                >
                  Cek Nilai
                </button>{" "}
                <br></br>
              </li>
            </>
          ))}
        </ul>
      </main>

      <footer>
        <h4>footer</h4>
      </footer>
      <div>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossorigin="anonymous"
        ></Script>
      </div>
    </div>
  );
}
